//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compdetail
    {
        public int compid { get; set; }
        public int empid { get; set; }
        public string dept { get; set; }
        public string problem { get; set; }
        public string status { get; set; }
        public Nullable<long> contact { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
